# yaml-language-server: $schema=https://compose-spec.github.io/compose-spec.json
services:
  server:
    container_name: server
    build:
      context: ./services/server
      dockerfile: Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=server
    - SERVER_PORT=5678
    - STORAGE_DIR=/tmp/bets.csv
    - AGENCY_QUORUM_MIN=2
  client1:
    container_name: client1
    build:
      context: ./services/client
      dockerfile: Dockerfile
    environment:
    - AGENCY_ID=1
    - SERVER_HOST=server
    - SERVER_PORT=5678
    - INPUT_FILE=/input/input-1.csv
    - OUTPUT_FILE=/output/winners-1.csv
    - BATCH_SIZE=2
    volumes:
    - ./input:/input:ro
    - ./output:/output:rw
    depends_on:
    - server

  client2:
    container_name: client2
    build:
      context: ./services/client
      dockerfile: Dockerfile
    environment:
    - AGENCY_ID=2
    - SERVER_HOST=server
    - SERVER_PORT=5678
    - INPUT_FILE=/input/input-2.csv
    - OUTPUT_FILE=/output/winners-2.csv
    - BATCH_SIZE=2
    volumes:
    - ./input:/input:ro
    - ./output:/output:rw
    depends_on:
    - server