
services:
  server:
    container_name: server
    build:
      context: ./services/server
      dockerfile: Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=server
    - SERVER_PORT=5678
    - STORAGE_DIR=/app/bets.csv
    volumes:
    - ./output/server:/app:rw
  client1:
    container_name: client1
    build:
      context: ./services/client
      dockerfile: Dockerfile
    environment:
    - AGENCY_ID=1
    - SERVER_HOST=server
    - SERVER_PORT=5678
    - INPUT_FILE=/app/input.csv
    - OUTPUT_DIR=/app/output
    - BATCH_SIZE=2
    volumes:
    - ./input/input-test-1.csv:/app/input.csv:ro
    - ./output:/app/output:rw
    depends_on:
    - server

  client2:
    container_name: client2
    build:
      context: ./services/client
      dockerfile: Dockerfile
    environment:
    - AGENCY_ID=2
    - SERVER_HOST=server
    - SERVER_PORT=5678
    - INPUT_FILE=/app/input.csv
    - OUTPUT_DIR=/app/output
    - BATCH_SIZE=2
    volumes:
    - ./input/input-test-2.csv:/app/input.csv:ro
    - ./output:/app/output:rw
    depends_on:
    - server
